### ISSUE TITLE
Not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by UrstHorst** [rollersteaam/chronobreak#2]
Hey, 

I really love this thing. Best pomodoro timer out there, imho. Unfortunately there seemes to be a problem with the electron wrapper since Ubuntu 20.04. In 19.10 everthing was fine. Now I get this error, when I try to open the timer.

> (chronobreak:82690): Pango-ERROR **: 19:03:07.339: Harfbuzz version too old (1.4.2)

Some research on git hub suggests that this error can only be avoided, if the developers update to the latest version of electron.

You'd be a hero to me!

**Comment by rollersteaam** [comment]
Yo @UrstHorst, thank you for your kind words! Really glad you like it.

I've prepared a new release for you, try it out and tell me if it works. Can't really test on my machine since I don't have Linux installed.

https://github.com/rollersteaam/chronobreak/releases/tag/v1.1.1

**Comment by UrstHorst** [comment]
Thank you so much for your effort. I've tested it and sadly it's not possible to move the time up to start the counter using the mouse. Otherwise the app ist starting flawlessly. Could this be a problem on my side of things?

Cheers

**Comment by rollersteaam** [comment]
Thanks for baring with me, turns out I didn't properly test it before I sent it to you! D: The problem was replicable on my machine and therefore easily fixed. Turned out to be some new security settings introduced by Electron which I needed to handle. Should be all good now :)

https://github.com/rollersteaam/chronobreak/releases/tag/v1.1.2

Thanks again for opening an issue for Linux machines, you've been a great help
